// Code generated by cmd/genmounts. DO NOT EDIT.

package components

import rl "github.com/gen2brain/raylib-go/raylib"

// VehicleMountSet holds the model-space points the SIM reads: metres, forward
// +Z, up +Y, left +X, relative to the hull origin. Turret-mounted points are
// recorded at turret yaw 0; for a smoke cloud twelve metres across that is
// well inside the noise, and nothing here is precise enough to aim with.
type VehicleMountSet struct {
	Smoke    rl.Vector3
	HasSmoke bool
}

var VehicleMounts = [VehicleKindCount][AssetSideCount]VehicleMountSet{
	VehicleBTR: {
		SideWest: {Smoke: rl.Vector3{X: -0.14805, Y: 2.6913, Z: 0.8161}, HasSmoke: true}, // commando
	},
	VehicleBMP: {
		SideWest: {Smoke: rl.Vector3{X: -0.60625, Y: 1.9818, Z: 1.2727}, HasSmoke: true}, // m113
	},
	VehicleTank: {
		SideWest: {Smoke: rl.Vector3{X: -0, Y: 2.0257, Z: 1.1319}, HasSmoke: true}, // tank_w
	},
	VehicleATCarrier: {
		SideWest: {Smoke: rl.Vector3{X: -0.23, Y: 1.82, Z: 0.4226}, HasSmoke: true}, // ferret
	},
	VehicleCar: {
		SideWest: {Smoke: rl.Vector3{X: 0, Y: 2.745, Z: 0.2209}, HasSmoke: true}, // mrap_2
	},
}
