// genmounts bakes the sim-facing attachment points out of the asset manifest
// into a checked-in Go table.
//
//	go run ./cmd/genmounts
//
// Why generate instead of reading the manifest at runtime: a mount that the sim
// uses is part of the simulation. Reading it from disk would make a headless
// gate (no GL, no model upload) disagree with a rendered run, and would turn
// a re-export of a model into a silent behaviour change. Generated code makes
// the same edit a visible diff, and every replay gate keeps working.
//
// Cosmetic mounts — exhaust, headlights — are NOT here. Those are read live by
// the renderer, where nothing they do can reach a hash.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"rts-go/components"
)

type mount struct {
	ID   string     `json:"id"`
	Part string     `json:"part"`
	Pos  [3]float32 `json:"pos"`
}

type asset struct {
	Name   string  `json:"name"`
	Mounts []mount `json:"mounts"`
}

const manifestPath = "assets/models/manifest.json"
const outPath = "components/vehicle_mounts_gen.go"

func main() {
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genmounts: %v\n", err)
		os.Exit(1)
	}
	var list []asset
	if err := json.Unmarshal(raw, &list); err != nil {
		fmt.Fprintf(os.Stderr, "genmounts: %v\n", err)
		os.Exit(1)
	}
	byName := make(map[string]*asset, len(list))
	for i := range list {
		byName[list[i].Name] = &list[i]
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/genmounts. DO NOT EDIT.\n\n")
	b.WriteString("package components\n\n")
	b.WriteString("import rl \"github.com/gen2brain/raylib-go/raylib\"\n\n")
	b.WriteString(`// VehicleMountSet holds the model-space points the SIM reads: metres, forward
// +Z, up +Y, left +X, relative to the hull origin. Turret-mounted points are
// recorded at turret yaw 0; for a smoke cloud twelve metres across that is
// well inside the noise, and nothing here is precise enough to aim with.
type VehicleMountSet struct {
	Smoke    rl.Vector3
	HasSmoke bool
}

`)
	b.WriteString("var VehicleMounts = [VehicleKindCount][AssetSideCount]VehicleMountSet{\n")
	sides := [...]string{"SideWest", "SideEast"}
	for k := 0; k < int(components.VehicleKindCount); k++ {
		rows := make([]string, 0, 2)
		for si, name := range components.VehicleAssetName[k] {
			if name == "" {
				continue
			}
			a := byName[name]
			if a == nil {
				fmt.Fprintf(os.Stderr, "genmounts: %s/%s bound to %q which is not in the manifest\n",
					components.SpecForVehicle(components.VehicleKind(k)).Name, sides[si], name)
				continue
			}
			if row := smokeRow(a, sides[si], name); row != "" {
				rows = append(rows, row)
			}
		}
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\tVehicle%s: {\n", kindIdent(components.VehicleKind(k)))
		for _, r := range rows {
			b.WriteString(r)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genmounts: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genmounts: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote", outPath)
}

// smokeRow renders one side's launcher offset, or "" when the model has none.
func smokeRow(a *asset, side, name string) string {
	{
		var left, right *mount
		for i := range a.Mounts {
			switch a.Mounts[i].ID {
			case "smoke.launcher.left":
				left = &a.Mounts[i]
			case "smoke.launcher.right":
				right = &a.Mounts[i]
			}
		}
		if left == nil && right == nil {
			return ""
		}
		p := [3]float32{}
		switch {
		case left != nil && right != nil:
			for i := 0; i < 3; i++ {
				p[i] = (left.Pos[i] + right.Pos[i]) / 2
			}
		case left != nil:
			p = left.Pos
		default:
			p = right.Pos
		}
		return fmt.Sprintf("\t\t%s: {Smoke: rl.Vector3{X: %g, Y: %g, Z: %g}, HasSmoke: true}, // %s\n",
			side, p[0], p[1], p[2], name)
	}
}

// kindIdent recovers the enum identifier from the spec name; the spec table is
// the only place that pairing exists.
func kindIdent(k components.VehicleKind) string {
	n := components.SpecForVehicle(k).Name
	n = strings.ReplaceAll(n, " ", "")
	switch n {
	case "ATCarrier":
		return "ATCarrier"
	}
	return n
}
